services:
  app:
    image: ghcr.io/azamrahim/devsecops-lab:latest
    container_name: legal-things
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/legal_things
    ports:
      - "8080:8080"