name: CI

on: push

permissions:
  contents: read
  packages: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t lab-app:latest app/

      # - name: Scan image with Trivy (FAIL on HIGH/CRITICAL)
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: lab-app:latest
      #     severity: HIGH,CRITICAL
      #     exit-code: "1"
      #     ignore-unfixed: true
      #     trivyignores: .trivyignore

      - name: Tag image for GHCR
        run: |
          IMG="${GHCR_IMAGE,,}"
          docker tag lab-app:latest "$IMG:latest"
          docker tag lab-app:latest "$IMG:${{ github.sha }}"

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          IMG="${GHCR_IMAGE,,}"
          docker push "$IMG:latest"
          docker push "$IMG:${{ github.sha }}"